services:
  build-manager:
    image: builder-manager:latest
    container_name: aur-cache
    volumes:
      - "./config:/config:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "repository:/usr/share/nginx/html:rw"
      - "package-staging:/package-staging:rw"
      - "aur-package-list:/aur-package-list:rw"
    environment:
      - "PUID=1000"
      - "DOCKER_PGID=969"
#      - "BASE_URL=docker-aur-cache.localhost"
#      - "TRAEFIK_NETWORK=traefik-reverse-proxy"
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  package-staging:
  aur-package-list:
  repository: