export default interface AurRpcApiPackage {
    Conflicts: Array<string>,
    Depends: Array<string>,
    Description: string,
    FirstSubmitted: number,
    LastModdified: number,
    ID: number,
    Keywords: Array<string>,
    License: Array<string>,
    Maintainer: string,
    MakeDepends: Array<string>,
    Name: string,
    NumVotes: number,
    OptDepends: Array<string>,
    OutOfDate: string|null,
    PackageBase: string,
    PackageBaseID: number,
    Popularity: number,
    Submitter: string,
    URL: string,
    URLPath: string,
    Version: string,
};
