export default interface PackageApiPackage {
    pkgname: string,
    pkgbase: string,
    repo: string,
    arch: string,
    pkgver: string,
    pkgrel: string,
    epoch: number,
    pkgdesc: string,
    url: string,
    filename: string,
    compressed_size: number,
    installed_size: number,
    build_date: string,
    last_update: string,
    flag_date: string|null,
    maintainers: Array<string>,
    packager: string,
    groups: Array<string>,
    licenses: Array<string>,
    conflicts: Array<string>,
    provides: Array<string>,
    replaces: Array<string>,
    depends: Array<string>,
    optdepends: Array<string>,
    makedepends: Array<string>,
    checkdepends: Array<string>,
}
